"""RoMAE for light curves.

Continuous rotary transformers for asynchronous multi-band light curves, with
axial p-RoPE and nD-RoPE position encodings, softmax or linear attention, and
three pretraining frameworks: masked autoencoding
(:class:`RoMAEForPreTraining`), LeJEPA (:class:`LeJEPA`) and LeWorldModel
(:class:`LeWorldModel`).
"""

from .analysis import (
    TimeEncodingReport,
    nd_rope_theta_bound,
    periodogram,
    plot_time_encoding,
    rotary_kernel,
    rotary_ladder,
    rotary_wavelengths,
    sampling_stats,
    spectral_support,
    suggest_time_encoding,
    time_encoding,
    time_shuffle_score,
    timescales_for,
    wave_vectors,
)
from .data import (
    CLASSES,
    DEFAULT_SURVEYS,
    PC_BANDS,
    PC_SUPERCLASSES,
    PHOEBE_BANDS,
    PHOEBE_MORPHOLOGIES,
    LightCurveDataset,
    Record,
    SimConfig,
    SurveyConfig,
    ViewConfig,
    collate,
    load_pc,
    load_phoebe,
    make_views,
    normalize,
    sample_view,
    simulate,
    time_series,
)
from .frames import (
    FrameConfig,
    FrameDataset,
    collate_frames,
    frame_grid,
    sample_frames,
)
from .lejepa import LeJEPA, LeJEPAOutput, SlicedEppsPulley, mlp
from .lewm import (
    ActionEncoder,
    ARPredictor,
    LeWMOutput,
    LeWorldModel,
    lewm_mlp,
    straightness,
)
from .model import (
    MAEOutput,
    RoMAE,
    RoMAEForClassification,
    RoMAEForPreTraining,
    gen_mask,
)
from .rope import (
    AxialRope,
    BlockRope,
    SimplexRope,
    layout,
    min_axial_dim,
    min_simplex_scales,
    resample_ladder,
)
from .tokenize import BAND_WAVELENGTHS_NM, Tokens, tokenize, wavelengths_for
from .transformer import SIZES, Transformer, TransformerConfig, attention_mask

__all__ = [
    "ARPredictor",
    "ActionEncoder",
    "AxialRope",
    "BAND_WAVELENGTHS_NM",
    "BlockRope",
    "CLASSES",
    "DEFAULT_SURVEYS",
    "FrameConfig",
    "FrameDataset",
    "LeJEPA",
    "LeJEPAOutput",
    "LeWMOutput",
    "LeWorldModel",
    "LightCurveDataset",
    "MAEOutput",
    "PC_BANDS",
    "PC_SUPERCLASSES",
    "PHOEBE_BANDS",
    "PHOEBE_MORPHOLOGIES",
    "Record",
    "RoMAE",
    "RoMAEForClassification",
    "RoMAEForPreTraining",
    "SIZES",
    "SimConfig",
    "SimplexRope",
    "SlicedEppsPulley",
    "SurveyConfig",
    "TimeEncodingReport",
    "Tokens",
    "Transformer",
    "TransformerConfig",
    "ViewConfig",
    "attention_mask",
    "collate",
    "collate_frames",
    "frame_grid",
    "gen_mask",
    "layout",
    "lewm_mlp",
    "load_pc",
    "load_phoebe",
    "make_views",
    "min_axial_dim",
    "min_simplex_scales",
    "mlp",
    "nd_rope_theta_bound",
    "normalize",
    "periodogram",
    "plot_time_encoding",
    "resample_ladder",
    "rotary_kernel",
    "rotary_ladder",
    "rotary_wavelengths",
    "sample_frames",
    "sample_view",
    "sampling_stats",
    "simulate",
    "spectral_support",
    "straightness",
    "suggest_time_encoding",
    "time_encoding",
    "time_series",
    "time_shuffle_score",
    "timescales_for",
    "tokenize",
    "wave_vectors",
    "wavelengths_for",
]
__version__ = "0.2.0"
